server:
    port: 8080
    compression:
        enabled: true
        mime-types: application/json
    servlet:
        context-path: /wishlist
spring:
    application:
        name: ms-wishlist
    data:
        mongodb:
            uri: ${WISHLIST_MONGODB_URI}
springdoc:
    packagesToScan: com.wishlist.api.entrypoint
    pathsToMatch: /**
    swagger-ui:
        disable-swagger-default-url: true
        doc-expansion: none
        tagsSorter: alpha